#!/bin/bash
# ──────────────────────────────────────────────────────────────
# Fedora DNF GUI Tool — Installer Script
# Author: Greg.Tech (https://greg.tech)
# License: GPL-3.0
#
# Usage:
#   sudo ./install.sh          Install the application
#   sudo ./install.sh remove   Uninstall the application
# ──────────────────────────────────────────────────────────────

set -e

APP_NAME="dnf-gui"
APP_DISPLAY_NAME="DNF Package Manager"
INSTALL_DIR="/opt/dnf-gui"
BIN_LINK="/usr/local/bin/dnf-gui"
DESKTOP_FILE="/usr/share/applications/dnf-gui.desktop"
ICON_DIR="/usr/share/icons/hicolor/scalable/apps"
ICON_FILE="${ICON_DIR}/dnf-gui.svg"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_header() {
    echo ""
    echo -e "${BLUE}╔══════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║${NC}  🚀 ${APP_DISPLAY_NAME} Installer              ${BLUE}║${NC}"
    echo -e "${BLUE}║${NC}     by Greg.Tech                                ${BLUE}║${NC}"
    echo -e "${BLUE}╚══════════════════════════════════════════════════╝${NC}"
    echo ""
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
        echo ""
        echo "  Usage: sudo ./install.sh"
        echo "  Usage: sudo ./install.sh remove"
        exit 1
    fi
}

check_fedora() {
    if [ ! -f /etc/fedora-release ]; then
        echo -e "${YELLOW}Warning: This doesn't appear to be a Fedora system.${NC}"
        echo "This application is designed for Fedora Linux."
        read -p "Continue anyway? (y/N) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi
}

install_dependencies() {
    echo -e "${BLUE}[1/5]${NC} Installing system dependencies..."

    # Check if python3-pyqt6 is available/installed
    if python3 -c "import PyQt6" 2>/dev/null; then
        echo -e "  ${GREEN}✓${NC} PyQt6 is already installed"
    else
        echo "  Installing python3-pyqt6..."
        dnf install -y python3-pyqt6 2>/dev/null || {
            echo -e "  ${YELLOW}!${NC} python3-pyqt6 not found in repos, trying pip..."
            pip3 install PyQt6 2>/dev/null || {
                echo -e "  ${RED}✗ Could not install PyQt6. Please install it manually:${NC}"
                echo "    sudo dnf install python3-pyqt6"
                echo "    or: pip3 install PyQt6"
                exit 1
            }
        }
        echo -e "  ${GREEN}✓${NC} PyQt6 installed"
    fi

    # Ensure python3 is available
    if ! command -v python3 &>/dev/null; then
        echo -e "  ${RED}✗ python3 not found${NC}"
        exit 1
    fi
    echo -e "  ${GREEN}✓${NC} Python3 found: $(python3 --version)"
}

install_app() {
    echo -e "${BLUE}[2/5]${NC} Installing application to ${INSTALL_DIR}..."

    # Create install directory
    mkdir -p "${INSTALL_DIR}"

    # Copy application files
    cp -r src/dnf_gui "${INSTALL_DIR}/"

    echo -e "  ${GREEN}✓${NC} Application files copied"
}

install_launcher() {
    echo -e "${BLUE}[3/5]${NC} Creating launcher script..."

    # Create the launcher script
    cat > "${BIN_LINK}" << 'LAUNCHER'
#!/bin/bash
# DNF Package Manager — Launcher
# Generated by install.sh

export PYTHONPATH="/opt/dnf-gui:${PYTHONPATH}"
exec python3 -m dnf_gui "$@"
LAUNCHER

    chmod +x "${BIN_LINK}"
    echo -e "  ${GREEN}✓${NC} Launcher created at ${BIN_LINK}"
}

install_desktop() {
    echo -e "${BLUE}[4/5]${NC} Installing desktop entry..."

    # Install icon
    mkdir -p "${ICON_DIR}"
    if [ -f "assets/icons/app_icon.svg" ]; then
        cp "assets/icons/app_icon.svg" "${ICON_FILE}"
        echo -e "  ${GREEN}✓${NC} Icon installed"
    fi

    # Create desktop entry
    cat > "${DESKTOP_FILE}" << EOF
[Desktop Entry]
Type=Application
Name=DNF Package Manager
GenericName=Package Manager
Comment=Modern GUI package manager for Fedora Linux — by Greg.Tech
Exec=${BIN_LINK}
Icon=dnf-gui
Terminal=false
Categories=System;PackageManager;Settings;
Keywords=dnf;package;manager;update;install;remove;fedora;flatpak;
StartupNotify=true
StartupWMClass=dnf-package-manager
X-GNOME-UsesNotifications=true
EOF

    echo -e "  ${GREEN}✓${NC} Desktop entry installed"
}

post_install() {
    echo -e "${BLUE}[5/5]${NC} Finalizing..."

    # Update desktop database
    if command -v update-desktop-database &>/dev/null; then
        update-desktop-database /usr/share/applications/ 2>/dev/null || true
    fi

    # Update icon cache
    if command -v gtk-update-icon-cache &>/dev/null; then
        gtk-update-icon-cache /usr/share/icons/hicolor/ 2>/dev/null || true
    fi

    echo -e "  ${GREEN}✓${NC} Desktop database updated"
}

do_install() {
    print_header
    check_root
    check_fedora

    echo -e "${GREEN}Installing ${APP_DISPLAY_NAME}...${NC}"
    echo ""

    install_dependencies
    install_app
    install_launcher
    install_desktop
    post_install

    echo ""
    echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  ✅  Installation complete!                      ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "  You can now:"
    echo ""
    echo -e "  • Run from terminal:  ${BLUE}dnf-gui${NC}"
    echo -e "  • Find in KDE menu:   ${BLUE}${APP_DISPLAY_NAME}${NC}"
    echo ""
    echo -e "  To uninstall:         ${YELLOW}sudo ./install.sh remove${NC}"
    echo ""
}

do_remove() {
    print_header
    check_root

    echo -e "${YELLOW}Uninstalling ${APP_DISPLAY_NAME}...${NC}"
    echo ""

    # Remove application files
    if [ -d "${INSTALL_DIR}" ]; then
        rm -rf "${INSTALL_DIR}"
        echo -e "  ${GREEN}✓${NC} Removed ${INSTALL_DIR}"
    fi

    # Remove launcher
    if [ -f "${BIN_LINK}" ]; then
        rm -f "${BIN_LINK}"
        echo -e "  ${GREEN}✓${NC} Removed ${BIN_LINK}"
    fi

    # Remove desktop entry
    if [ -f "${DESKTOP_FILE}" ]; then
        rm -f "${DESKTOP_FILE}"
        echo -e "  ${GREEN}✓${NC} Removed desktop entry"
    fi

    # Remove icon
    if [ -f "${ICON_FILE}" ]; then
        rm -f "${ICON_FILE}"
        echo -e "  ${GREEN}✓${NC} Removed icon"
    fi

    # Update desktop database
    if command -v update-desktop-database &>/dev/null; then
        update-desktop-database /usr/share/applications/ 2>/dev/null || true
    fi

    echo ""
    echo -e "${GREEN}✅  ${APP_DISPLAY_NAME} has been uninstalled.${NC}"
    echo ""
}

# ─── Main ───────────────────────────────────────────────────

case "${1}" in
    remove|uninstall|--remove|--uninstall|-r)
        do_remove
        ;;
    *)
        do_install
        ;;
esac
